Repository GoodBadChad/good-bad-chad-br, pull requests merged in 2024-01, with the labels that each got.

#23 Nathan
  fonts/vt323/SIL Open Font License.txt
  fonts/vt323/VT323-Regular.ttf
  js/classes/crosshair.js
  js/classes/dialog_bubble.js
  js/classes/draw_image.js
  js/classes/entities/dialog_bubble.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/classes/game_engine copy.js
  js/classes/inventory.js
  js/classes/slingshot.js
  js/scripts/dialog/dialog.js
  js/scripts/dimension/playground_dimension.js
  js/scripts/temp/dialog.js
  js/scripts/temp/dialogTest.js
  js/scripts/util.js
  sprites/crosshair.png
Labels: enhancement

#29 Improved crosshair and fixed mouse tracking
  index.html
  js/classes/entities/foreground/crosshair.js
  js/classes/entities/foreground/dialog_bubble.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/classes/entities/midground/weapon/slingshot.js
  js/classes/game_engine.js
  js/scripts/dimension/playground_dimension.js
  js/scripts/util.js
  sprites/crosshair.png
  sprites/mouse_cursor.png
Labels: enhancement

#54 Implement TileMap and a Map Script.
  index.html
  js/classes/dimension.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/scripts/dimension/playground_dimension.js
  js/scripts/dimension/village_dimension.js
  js/scripts/tileMaps/playground.js
  tileMapIn.txt
Labels: enhancement, help wanted

#60 Implement Sprint and Dash mechanics. Debugged.
  js/classes/dimension.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/classes/game_engine.js
  js/scripts/dimension/playground_dimension.js
  js/scripts/dimension/village_dimension.js
  js/scripts/tileMaps/playground.js
Labels: enhancement

#62 Merge Vector class.
  index.html
  js/classes/vector.js
Labels: enhancement

#79 Push Decoration class.
  js/classes/entities/background/decoration.js
  js/classes/entities/background/village/houses.js
  sprites/chad_house.png
  sprites/mayor_house.png
  sprites/tree.png
Labels: enhancement

#78 Added Zones to replace dimensions!!
  index.html
  js/classes/camera.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/classes/game_engine.js
  js/classes/zone.js
  js/scripts/main.js
  js/scripts/tile_maps/playground.js
  js/scripts/zone_loaders/factory_zone_loaders.js
  js/scripts/zone_loaders/lava_zone_loaders.js
  js/scripts/zone_loaders/mountain_zone_loaders.js
  js/scripts/zone_loaders/playground_zone_loaders.js
  js/scripts/zone_loaders/spooky_zone_loaders.js
  js/scripts/zone_loaders/village_zone_loaders.js
  js/scripts/zone_loaders/woods_zone_loaders.js
Labels: enhancement

#80 Merge Decoration class.
  js/classes/entities/background/decoration.js
  sprites/chad_house.png
  sprites/mayor_house.png
  sprites/tree.png
Labels: enhancement

#85 Travel between zones!
  index.html
  js/classes/animator.js
  js/classes/asset_manager.js
  js/classes/entities/background/decoration.js
  js/classes/entities/background/sun.js
  js/classes/entities/midground/border.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/classes/game_engine.js
  js/classes/zone.js
  js/scripts/main.js
  js/scripts/util.js
  js/scripts/zone_loaders/village_zone_loaders.js
Labels: enhancement

#83 Implement chad.js and refactor code.
  index.html
  js/classes/camera.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/classes/game_engine.js
  js/scripts/main.js
  js/scripts/zone_loaders/village_zone_loaders.js
Labels: enhancement

#89 Push animal changes.
  js/classes/entities/foreground/health_bar.js
  js/classes/entities/midground/enemies/village/bunny.js
  js/classes/entities/midground/enemies/village/snake.js
  js/scripts/util.js
Labels: enhancement

#92 Fix Slingshot and Crosshair.
  js/classes/asset_manager.js
  js/classes/entities/foreground/crosshair.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/weapon/slingshot.js
  js/classes/game_engine.js
  js/classes/zone.js
Labels: bug

#96 Add Basic Combat.
  index.html
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/enemies/village/snake.js
  js/classes/entities/midground/weapon/projectile.js
  js/classes/zone.js
  js/scripts/zone_loaders/playground_zone_loaders.js
Labels: enhancement

#103 Implement a funcitoning tile map for Caleb's zone in the playground and a tool for making template tile maps.
  dev_tools_temp/MakeMap.java
  dev_tools_temp/MapMaker.java
  index.html
  js/classes/zone.js
  js/scripts/tile_maps/caleb_zone_playground.js
  js/scripts/tile_maps/playground.js
  js/scripts/zone_loaders/playground_zone_loaders.js
Labels: enhancement

#105 Fixed syntax error.
  js/scripts/zone_loaders/playground_zone_loaders.js
Labels: bug

#106 Chad switches zones.
  js/classes/entities/midground/chad.js
  js/scripts/dialog/playground_dialog.js
Labels: bug fix

#102 Add Sword entity.
  js/classes/asset_manager.js
  js/classes/entities/midground/weapon/sword.js
  js/classes/game_engine.js
  js/classes/zone.js
  sprites/swords.png
Labels: enhancement

#114 Update index.html.
  css/general.css
  index.html
Labels: enhancement

#115 Add OverheadIcons, preliminary dialog.
  index.html
  js/classes/asset_manager.js
  js/classes/entities/foreground/dialog_bubble.js
  js/classes/entities/foreground/overhead_icon.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/scripts/dialog/playground_dialog.js
  js/scripts/dimension/playground_dimension.js
  js/scripts/util.js
  js/scripts/zone_loaders/playground_zone_loaders.js
  sprites/html_tab_icon.png
  sprites/overhead_icon.png
Labels: enhancement, bug fix
