Repository GoodBadChad/good-bad-chad-br, pull requests merged in 2024-02, with the labels that each got.

#118 Added in conversations!
  index.html
  js/classes/asset_manager.js
  js/classes/camera.js
  js/classes/conversation.js
  js/classes/dimension.js
  js/classes/entities/background/decoration.js
  js/classes/entities/foreground/dialog_bubble.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/classes/entities/midground/weapon/projectile.js
  js/classes/entities/midground/weapon/sword.js
  js/classes/game_engine.js
  js/scripts/conversation_loaders/main_conversation_loader.js
  js/scripts/conversation_loaders/playground_conversation_loaders.js
  js/scripts/dialog/playground_dialog.js
  js/scripts/util.js
  js/scripts/zone_loaders/playground_zone_loaders.js
  sprites/dialog_bubble.png
  sprites/text-bubble.png
Labels: enhancement, bug fix

#124 Add EnemyBase class, Yeti, and other enemy-related improvements.
  index.html
  js/classes/entities/midground/enemies/enemyBase.js
  js/classes/entities/midground/enemies/slime.js
  js/classes/entities/midground/enemies/snowy/yeti.js
  js/classes/entities/midground/enemies/village/bunny.js
  js/classes/entities/midground/enemies/village/snake.js
  js/classes/zone.js
  js/scripts/util.js
  js/scripts/zone_loaders/playground_zone_loaders.js
  sprites/yeti.png
Labels: enhancement

#125 Implement village and field zones and update spritesheets in use for characters. Implement basic weather system.
  .DS_Store
  dev_tools_temp/MakeMap.java
  index.html
  js/.DS_Store
  js/classes/asset_manager.js
  js/classes/entities/background/decoration.js
  js/classes/entities/background/sun.js
  js/classes/entities/foreground/dialog_bubble.js
  js/classes/entities/foreground/hud.js
  js/classes/entities/midground/block.js
  js/classes/entities/midground/border.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/npc/village/blacksmith.js
  js/classes/entities/midground/npc/village/mayor.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/classes/entities/midground/rain.js
  js/classes/entities/midground/weapon/sword.js
  js/classes/zone.js
  js/scripts/tile_maps/field_tilemap.js
  js/scripts/tile_maps/village_tilemap.js
  js/scripts/util.js
  js/scripts/zone_loaders/playground_zone_loaders.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sprites/CHAD1.png
  sprites/CHAD2.png
  sprites/CHAD3.png
  sprites/CHAD4.png
  sprites/blacksmith.png
  sprites/blocks.png
  sprites/blocks.pngh.png
  sprites/blocksModified.png
  sprites/cloud1.png
  sprites/cloud2.png
  sprites/cloud3.png
  sprites/grass.png
  sprites/mayor.png
  sprites/rain_drop.png
  sprites/rain_drop_left.png
  sprites/rain_drop_right.png
  sprites/tree_spruce.png
Labels: enhancement

#131 Pr128 2
  .DS_Store
  .gitignore
  index.html
  js/classes/asset_manager.js
  js/classes/entities/foreground/dialog/conversation.js
  js/classes/entities/foreground/dialog/decision_bubble.js
  js/classes/entities/foreground/dialog/dialog_bubble.js
  js/classes/entities/foreground/hud.js
  js/classes/entities/midground/chad.js
  js/classes/game_engine.js
  js/scripts/conversation_loaders/playground_conversation_loaders.js
  js/scripts/tile_maps/village_tilemap.js
  js/scripts/util.js
  js/scripts/zone_loaders/playground_zone_loaders.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sprites/speaker_chad.png
Labels: bug fix

#129 Add enemy animations.
  js/classes/entities/midground/enemies/enemyBase.js
  js/classes/entities/midground/enemies/slime.js
  js/classes/entities/midground/enemies/village/bunny.js
  js/classes/entities/midground/enemies/village/snake.js
  sprites/bunny.png
  sprites/slimes.png
  sprites/snake.png
Labels: enhancement

#132 Bug fixes.
  js/classes/entities/foreground/hud.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/enemies/enemyBase.js
  js/classes/entities/midground/weapon/sword.js
Labels: documentation, bug fix

#137 Add Chad's Death.
  index.html
  js/classes/animator.js
  js/classes/entities/foreground/death_screen.js
  js/classes/entities/foreground/hud.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/enemies/enemyBase.js
  js/classes/entities/midground/enemies/village/snake.js
  js/classes/entities/midground/weapon/slingshot.js
  js/classes/entities/midground/weapon/sword.js
  js/classes/game_engine.js
  js/scripts/tile_maps/field_tilemap.js
  js/scripts/tile_maps/village_tilemap.js
  js/scripts/zone_loaders/playground_zone_loaders.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sprites/CHAD1.png
  sprites/dash-cooldown.png
Labels: enhancement, bug fix

#139 Dialog is fully functional, including affecting story. Tutorial dialog/papa chad actions are complete.
  index.html
  js/classes/entities/foreground/dialog/conversation.js
  js/classes/entities/foreground/dialog/dialog_bubble.js
  js/classes/entities/midground/enemies/village/bunny.js
  js/classes/entities/midground/enemies/village/snake.js
  js/classes/entities/midground/npc/village/papa_chad.js
  js/scripts/conversation_loaders/main_conversation_loader.js
  js/scripts/conversation_loaders/village_conversation_loader.js
  js/scripts/main.js
  js/scripts/zone_loaders/village_zone_loaders.js
Labels: enhancement

#140 Fix reversed animations skipping.
  js/classes/animator.js
Labels: bug fix

#145 Bugfixes and Food Drops
  index.html
  js/classes/animator.js
  js/classes/asset_manager.js
  js/classes/entities/foreground/dash_cooldown.js
  js/classes/entities/foreground/hud.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/collectables/food_drop.js
  js/classes/entities/midground/enemies/snowy/yeti.js
  js/classes/entities/midground/enemies/village/bunny.js
  js/classes/entities/midground/enemies/village/snake.js
  js/classes/entities/midground/weapon/projectile.js
  js/classes/entities/midground/weapon/slingshot.js
  js/classes/entities/midground/weapon/sword.js
  js/classes/inventory.js
  js/scripts/main.js
  js/scripts/util.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sfx/ding.mp3
  sfx/growl1.mp3
  sfx/growl2.mp3
  sfx/smash1.mp3
  sfx/smash2.mp3
  sfx/smash3.mp3
  sprites/cooldown.png
  sprites/dash-cooldown.png
Labels: enhancement, bug fix

#149 Ammo selection.
  js/classes/inventory.js
  js/scripts/util.js
Labels: enhancement, bug fix
