Repository GoodBadChad/good-bad-chad-br, pull requests merged in 2024-03, with the labels that each got.

#152 Update tilemap interpretor.
  dev_tools_temp/MakeMap.java
  index.html
  js/classes/entities/background/decoration.js
  js/classes/entities/foreground/precipitation.js
  js/classes/entities/foreground/weather_system.js
  js/classes/entities/midground/block.js
  js/classes/zone.js
  js/scripts/main.js
  js/scripts/tile_maps/cave_tilemap.js
  js/scripts/tile_maps/hill_tilemap.js
  js/scripts/tile_maps/village_tilemap.js
  js/scripts/tile_maps/woods_tilemap.js
  js/scripts/util.js
  js/scripts/zone_loaders/tilemap_interpreter.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sprites/CHAD1.png
  sprites/blocks.png
  sprites/cloud_dark1.aseprite
  sprites/cloud_dark1.png
  sprites/cloud_dark2.aseprite
  sprites/cloud_dark2.png
  sprites/cloud_dark3.aseprite
  sprites/cloud_dark3.png
  sprites/dark.aseprite
  sprites/dark.png
  sprites/grass.png
  sprites/lantern.aseprite
  sprites/lantern.png
  sprites/torch.png
Labels: enhancement

#151 Refactor Sword.
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/weapon/sword.js
  js/classes/zone.js
Labels: enhancement, bug fix

#153 Update to cave lighting and Chad pos.
  index.html
  js/classes/entities/midground/npc/village/blacksmith copy.js
  js/scripts/zone_loaders/tilemap_interpreter.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sprites/Sprite-0002.aseprite
  sprites/dark.png
  sprites/miner.aseprite
  sprites/miner.png
Labels: enhancement, bug fix

#155 Update fixing bug when loading hill zone.
  js/classes/entities/foreground/hud.js
  js/scripts/zone_loaders/village_zone_loaders.js
Labels: bug fix

#157 Update to hud.
  index.html
  js/classes/entities/background/decoration.js
  js/classes/entities/foreground/hud.js
  js/classes/entities/foreground/weather_system.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/portal.js
  js/classes/vector.js
  js/scripts/tile_maps/cave_tilemap.js
  js/scripts/util.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sprites/title.png
Labels: enhancement, bug fix

#158 Add start screen and controls menu.
  index.html
  js/classes/asset_manager.js
  js/classes/entities/foreground/ui/button.js
  js/classes/entities/foreground/ui/controls.js
  js/classes/entities/foreground/ui/death_screen.js
  js/classes/entities/foreground/ui/hud.js
  js/classes/entities/foreground/ui/start_menu.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/weapon/slingshot.js
  js/classes/game_engine.js
  js/classes/zone.js
  js/scripts/main.js
Labels: enhancement, bug fix

#159 Update to drawing hud after foreground blocks and loading Chad in the cave propperly.
  js/classes/entities/midground/chad.js
  js/scripts/zone_loaders/village_zone_loaders.js
Labels: bug fix

#156 Enhanced ammo
  js/classes/animator.js
  js/classes/asset_manager.js
  js/classes/entities/foreground/ammo_item.js
  js/classes/entities/foreground/ui/hud.js
  js/classes/entities/midground/block.js
  js/classes/entities/midground/chad.js
  js/classes/entities/midground/drops/ammo_drop.js
  js/classes/entities/midground/drops/food_drop.js
  js/classes/entities/midground/enemies/bunny.js
  js/classes/entities/midground/enemies/drill_bot.js
  js/classes/entities/midground/enemies/enemy_base.js
  js/classes/entities/midground/enemies/slime.js
  js/classes/entities/midground/enemies/snake.js
  js/classes/entities/midground/enemies/yeti.js
  js/classes/entities/midground/particle_effect.js
  js/classes/entities/midground/portal.js
  js/classes/entities/midground/water.js
  js/classes/entities/midground/weapon/bomb.js
  js/classes/entities/midground/weapon/broccoli.js
  js/classes/entities/midground/weapon/projectile_factory.js
  js/classes/entities/midground/weapon/rock.js
  js/classes/entities/midground/weapon/slimeball.js
  js/classes/entities/midground/weapon/slingshot.js
  js/classes/entities/midground/weapon/snowball.js
  js/classes/entities/midground/weapon/sus_snowball.js
  js/classes/inventory.js
  js/classes/status_effect.js
  js/classes/zone.js
  js/scripts/tile_maps/river_tilemap.js
  js/scripts/util.js
  js/scripts/zone_loaders/river_zone_loaders.js
  js/scripts/zone_loaders/tilemap_interpreter.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sfx/ammo_collect.mp3
  sprites/ammo_drops.png
  sprites/blocks.png
  sprites/projectile_the_rock.png
Labels: enhancement, bug fix

#160 Small fixes.
  js/classes/entities/foreground/ui/controls.js
  js/classes/entities/foreground/ui/hud.js
Labels: bug fix

#166 Update to cave zones, minor refactors and update to sprites.
  dev_tools_temp/MakeMap.java
  index.html
  js/classes/entities/background/decoration.js
  js/classes/entities/foreground/weather_system.js
  js/classes/zone.js
  js/scripts/tile_maps/cave_2_zone.js
  js/scripts/tile_maps/cave_tilemap.js
  js/scripts/zone_loaders/cave_zone_loaders.js
  js/scripts/zone_loaders/mountain_zone_loaders.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sprites/blocks.png
  sprites/crystal1green.png
  sprites/dark.aseprite
  sprites/dark.png
  sprites/greenspikecrystal1.png
  sprites/groupcrystals1.png
  sprites/groupcrystals2.png
  sprites/purplespikecrystal1.png
  sprites/spikecyrstalblue1.png
Labels: bug, enhancement, bug fix

#169 Update to cave and add end zone.
  dev_tools_temp/MakeMap.java
  index.html
  js/classes/entities/background/decoration.js
  js/classes/entities/foreground/dialog/dialog_bubble.js
  js/classes/entities/midground/npc/miner.js
  js/classes/game_engine.js
  js/classes/zone.js
  js/scripts/conversation_loaders/village_conversation_loader.js
  js/scripts/main.js
  js/scripts/temp/dialog.js
  js/scripts/tile_maps/cave_2_zone.js
  js/scripts/tile_maps/cave_tilemap.js
  js/scripts/tile_maps/end_tilemap.js
  js/scripts/tile_maps/river_tilemap.js
  js/scripts/util.js
  js/scripts/zone_loaders/cave_zone_loaders.js
  js/scripts/zone_loaders/end_zone_loader.js
  js/scripts/zone_loaders/mountain_zone_loaders.js
  js/scripts/zone_loaders/river_zone_loaders.js
  js/scripts/zone_loaders/village_zone_loaders.js
  sfx/mp3.zip
  sprites/miner.png
  sprites/npc.aseprite
  sprites/torch.png
  sprites/tower1.aseprite
  sprites/tower1.png
  sprites/towergroup1.aseprite
  sprites/towergroup1.png
  sprites/towergroup2.png
Labels: enhancement

#170 Add enemy jumping/climbing.
  index.html
  js/classes/entities/foreground/dialog/dialog_bubble.js
  js/classes/entities/foreground/ui/hud.js
  js/classes/entities/midground/enemies/drill_bot.js
  js/classes/entities/midground/enemies/enemy_base.js
  js/classes/entities/midground/enemies/wizard.js
  js/classes/entities/midground/portal.js
  js/classes/entities/midground/weapon/water_balloon.js
  js/scripts/conversation_loaders/end_conversation_loader.js
  js/scripts/conversation_loaders/main_conversation_loader.js
  js/scripts/main.js
  js/scripts/zone_loaders/end_zone_loader.js
  js/scripts/zone_loaders/mountain_zone_loaders.js
  js/scripts/zone_loaders/river_zone_loaders.js
  js/scripts/zone_loaders/village_zone_loaders.js
Labels: enhancement

#173 Implement End Zone.
  js/classes/entities/background/decoration.js
  js/classes/entities/foreground/weather_system.js
  js/classes/entities/midground/block.js
  js/scripts/tile_maps/end_tilemap.js
  js/scripts/util.js
  js/scripts/zone_loaders/end_zone_loader.js
  js/scripts/zone_loaders/mountain_zone_loaders.js
  js/scripts/zone_loaders/tilemap_interpreter.js
  js/scripts/zone_loaders/village_zone_loaders.js
  music/caleb_music/Cave Adventure.mp3
  music/caleb_music/ICE.mp3
  music/caleb_music/Intimidating1.mp3
  music/caleb_music/Thunder1.mp3
  sprites/blocks.png
  sprites/magicaltree1.aseprite
  sprites/magicaltree1.png
  sprites/magicaltree2.png
Labels: enhancement

#174 Update slope position when entering slope 2.
  js/scripts/zone_loaders/mountain_zone_loaders.js
Labels: bug fix
